import { Metadata } from "next";
import { Lexend, Akshar, Roboto, Inter } from "next/font/google";
import "./globals.css";

const lexend = Lexend({ subsets: ["latin"], variable: "--font-lexend" });
const akshar = Akshar({ subsets: ["latin"], variable: "--font-akshar" });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" }); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lexend.variable} ${akshar.variable} ${roboto.variable} ${inter.style.fontFamily}`}
    >
      <body>{children}</body>
    </html>
  );
}
